project:
  type: website

website:
  title: "R for Linguistics"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/daniela-palleschi
      - icon: twitter
        href: https://twitter.com/dpalleswho
      - icon: rss
        href: index.xml
format:
  html:
    toc: true
    code-tools: true
    theme: flatly
    css: styles.css
bibliography: references.bib
csl: apa.csl



